regions:
  Ausstellungen:
  - 0.0440359127832407
  - 0.7920193470374849
  - 0.4959384352287302
  - 0.9860943168077388
  Beschreibung:
  - 0.04574604531851219
  - 0.5259975816203144
  - 0.49807610089781956
  - 0.7889963724304716
  Datierung:
  - 0.27191107310816587
  - 0.23941958887545345
  - 0.49722103463018386
  - 0.3137847642079806
  Foto Notes:
  - 0.5053441641727234
  - 0.08282950423216445
  - 0.8550662676357418
  - 0.13059250302297462
  Gegenstand:
  - 0.042325780247969215
  - 0.006650544135429262
  - 0.9593843522873022
  - 0.07859733978234583
  Gewicht:
  - 0.27704147071398033
  - 0.3694074969770254
  - 0.49807610089781956
  - 0.4280532043530834
  Herkunft:
  - 0.2740487387772552
  - 0.08282950423216445
  - 0.49850363403163744
  - 0.23458282950423218
  Inv. Nr.:
  - 0.04489097905087644
  - 0.08101571946795647
  - 0.26934587430525864
  - 0.13663845223700122
  Literatur:
  - 0.5049166310389055
  - 0.532043530834341
  - 0.9773407439076528
  - 0.9842805320435308
  Masse:
  - 0.2736212056434374
  - 0.3174123337363966
  - 0.4959384352287302
  - 0.36638452237001207
  Material:
  - 0.0440359127832407
  - 0.23881499395405079
  - 0.2706284737067123
  - 0.4183796856106409
  Preis:
  - 0.735356990166738
  - 0.439540507859734
  - 0.864044463445917
  - 0.5175332527206772
  Standort:
  - 0.0440359127832407
  - 0.14026602176541716
  - 0.26934587430525864
  - 0.23458282950423218
  Vers. Wert:
  - 0.864044463445917
  - 0.437726723095526
  - 0.9747755451047456
  - 0.5187424425634825
  'am:':
  - 0.5040615647712697
  - 0.439540507859734
  - 0.7332193244976486
  - 0.5211608222490931
  'erworben von:':
  - 0.04489097905087644
  - 0.4365175332527207
  - 0.5019238991021804
  - 0.5223700120918985
